POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVtaWxzc29uIiwiaWQiOiI2N2EwOTUxMTUxNTM1NDFkZjNmN2Q5MjUiLCJpYXQiOjE3Mzg1ODA4NzF9.Owja1oPe6mwYGY0Mt6yVCx_R7SQKo2NCN5VLHbNj4hg

{
    "content": "Single page apps use token based auth",
    "important": true
}